### ISSUE TITLE
Fordele oppgaver:

### ISSUE THREAD

**Issue by Inzagio** [Inzagio/StartIT18Larvik#2]
Layout html og login.js:
SVG Graphs:
Register.js: Gruppe 1
Admin.js: Gruppe 3

**Comment by Inzagio** [comment]
Legger til at dette er ØNSKER, dersom en gruppe vil ha det samme som en annen så må dette ordnes

**Comment by LazyBoot** [comment]
Kanskje det skulle vært 1 kolonne for hver gruppe i "project" delen, også bare sette disse opp under "todo"?
Så kan hver gruppe dra inn det de vil ta seg av.

**Comment by LazyBoot** [comment]
Eller kanskje issues og labels kan brukes.

**Comment by ghost** [comment]
Vi i gruppe 1 tar gjerne registrering.js.
